defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *defaults
  database: Buynance_dev

test: &test
  <<: *defaults
  database: Buynance_test

production:
  <<: *defaults
  database: Buynance_prod

cucumber:
  <<: *test