defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: postgres
  password: postgres

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 10000

test: &test
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 10000
  database: Buynance_test

production:
  <<: *defaults
  database: Buynance_prod

cucumber:
  <<: *test